#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Mastodon total statuses
graph_vlabel statuses
graph_category mastodon
graph_args -l 0
statuses.label statuses
statuses.draw AREA
statuses.min 0
EOM
        exit 0;;
esac


printf "statuses.value "
echo "SELECT COUNT(*) FROM statuses;" | psql mastodon_production -tq | head -n 1



