#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Mastodon local accounts
graph_vlabel accounts
graph_category mastodon
graph_args -l 0
accounts.label local accounts
accounts.min 0
EOM
        exit 0;;
esac

printf "accounts.value "
echo "SELECT COUNT(*) FROM accounts WHERE domain IS NULL;" | psql mastodon_production -tq | head -n 1


