#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Mastodon local - Files size
graph_vlabel Files Size (MB)
graph_category mastodon
graph_args -l 0
graph_total Total
media.label Media Attachments
media.draw AREA
media.min 0
header.label Header
header.draw STACK
header.min 0
avatar.label Avatar
avatar.draw STACK
avatar.min 0
EOM
        exit 0;;
esac

printf "media.value "
echo `du -s /home/mastodon/live/public/system/media_attachments/ | awk '{print $1/1024;}'`

printf "header.value "
echo `du -s /home/mastodon/live/public/system/accounts/headers | awk '{print $1/1024;}'`

printf "avatar.value "
echo `du -s /home/mastodon/live/public/system/accounts/avatars | awk '{print $1/1024;}'`

